### ISSUE TITLE
Error when running acn

### ISSUE THREAD

**Issue by eperezv** [pereiramemo/AGS-and-ACN-tools#6]
Hello,

I am getting the following error when running acn. 
```
eduardo@eduardo-PC:/mnt/md0/DATA$ /home/eduardo/tools/AGS-and-ACN-tools/run_acn.sh G_T2BC2b_orfs.faa G_T2BC2b_ags.tsv acn_output --sample_name G_T2BC2b --verbose t nslots 4 --save_complementary_data t
Identifying 16S rRNA genes ...
Computing ACN ...
rm: cannot remove '/scratch//acn_output/G_T2BC2b.blast': No such file or directory
rm: cannot remove '/scratch//acn_output/G_T2BC2b.log': No such file or directory
rm: cannot remove '/scratch//acn_output': No such file or directory
rm: cannot remove '/scratch//acn_output/G_T2BC2b.fasta': No such file or directory
rm: cannot remove '/scratch//acn_output': No such file or directory
rsync: link_stat "/scratch/acn_output" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
rm: cannot remove '/scratch//acn_output': No such file or directory
```
I had no problems with ags

**Comment by eperezv** [comment]
I've checked that I might be using the wrong file (aa instead of nt). However, I have run into the same problem when using a fastq file as input

**Comment by pereiramemo** [comment]
Hi, 

I'm happy to see you are using our tools. 
These tools are designed to work with preprocessed fasta files (not fastq), which is critical to obtain an accurate annotation of the SCGs and 16S rRNA genes, and in turn, an accurate estimation of the AGS and ACN traits. 

To execute the ags tool, it is advisable to trim the reads to ~180bp (you can use the --max_length flag for this). 
Then, if you trim the reads, you must use these trimmed reads to execute the acn tool (the trimmed reads are found in the ags tool output folder). This is because the AGS number, which is use to compute the ACN, was computed for the trimmed fasta file.

Let me know if you have any further questions. 

Best, 

Emiliano

**Comment by eperezv** [comment]
Ok, thanks for the help. I've successfully run the pipeline by using raw sequences (150 nt). That was the problem, I was using contigs.
