### ISSUE TITLE
Weird sequences recognized as 16S

### ISSUE THREAD

**Issue by eperezv** [pereiramemo/AGS-and-ACN-tools#7]
Hello,
I am using this pipeline to estimate the average genome size and average copy numbers. After running the second script (ACN) and having a look at the fasta sequences (that should be 16S rRNA gene sequences (example_smrna.fasta), I got strange results.

For example, some sequences are like this:

>sample_15170 2:
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>ST84SAb_60153 1:
GAGGACGCGCTTCGGCATCTCAGAGCTCCCGGTCGACGAGGTAGAGGGGCCTGCTCGACGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

I guess they should not be recognized as 16S rRNA sequences and probably, the ACN is not properly estimated.

**Comment by pereiramemo** [comment]
Hi,

Thanks for letting us know about this issue. 
Our tool uses SortMeRNA (https://bioinfo.lifl.fr/RNA/sortmerna) to identify the 16S rRNA sequences. You can always adjust the --evalue, --min_idenity, and --min_length flags to set more stringent filtering.
Also be aware that, only the part of the read that aligns with the 16S rRNA gene is used to compute the coverage. Thus, these G homopolymers are not all necessarily used to compute the ACN.

Is the "sample_15170 2" sequence only Gs?
Can you check how many sequences do you have with this pattern and how many sequences are in total?

Cheers, 

Emiliano

**Comment by eperezv** [comment]
Ok. Thanks for the information.
Yes, sample_15170 is only Gs. I have also others that are Gs in the whole sequence (150nt). 

I've checked the blast info and all of them align with StaEpi81, whose accession number on NCBI is HG799999. That sequence contains several repeated Gs in the beginning in the sequence.

In any case, the blast intermediate file from the script shows the sequences either to have low identity percentage (74-93) or very high evalues (0.0128) for those with the highest identity. I guess the script is not considering those ones that are out of the default limits (evalue >1e-15). 

But It is weird that those sequences are part of the output files if they are not taken into account for the ACN calculation.

**Comment by pereiramemo** [comment]
Hi. 

Here are my comments:

 "... StaEpi81, whose accession number on NCBI is HG799999. That sequence contains several repeated Gs in the beginning in the sequence."
Ok, good to know.

"I guess the script is not considering those ones that are out of the default limits (evalue >1e-15)."
Yes, those are not considered. 

"But It is weird that those sequences are part of the output files if they are not taken into account for the ACN calculation."
The rationale behind this is to set a very low stringent criteria to run SrotMeRNA, so that its results can be reused to test different parameters (SrotMeRNA is can take several minutes to run).
I will add this explanation to the documentation. Thanks.

Let me know if there are any further questions,

Cheers, 

Emiliano

**Comment by eperezv** [comment]
Ok, great. Thanks for your answers. It is clearer now.
